import {StyleSheet} from 'react-native';
import {
  borderRadius,
  colors,
  fontFamily,
  fontSize,
  responsiveHeight,
  responsiveWidth,
  spaceVertical,
} from '../../styles/variables';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.nocolor,
  },
  img: {
    flex: 1,
    width: responsiveWidth(100),
    height: responsiveHeight(60),
    marginTop: spaceVertical.semiSmall,
    overflow: 'visible',
  },

  headertext: {
    fontFamily: fontFamily.bold,
    color: colors.white,
    fontSize: fontSize.extraLarge,
    marginTop: responsiveHeight(5),
    width: responsiveWidth(84),
  },
  mainContainer: {
    paddingBottom: 100,
    alignSelf: 'center',
    marginTop: spaceVertical.semiSmall,
  },
  pickerContainer: {
    width: responsiveWidth(80),
    borderWidth: 1,
    borderColor: colors.halfwhite,
    height: responsiveHeight(8),
    borderRadius: borderRadius.large,
    backgroundColor: colors.nocolor,
  },
  subTitle: {
    position: 'absolute',
    bottom: 50,
    backgroundColor: colors.nocolor,
    left: 10,
  },
  timeRow: {
    flexDirection: 'row',
    marginTop: spaceVertical.semiSmall,
    justifyContent: 'space-around',
  },
  timeContainer: {
    width: responsiveWidth(35),
    borderWidth: 1,
    borderColor: colors.halfwhite,
    height: responsiveHeight(8),
    borderRadius: borderRadius.large,
    backgroundColor: colors.nocolor,
    justifyContent: 'center',
  },
  timeTitle: {
    color: colors.white,
    alignSelf: 'center',
    fontFamily: fontFamily.semiBold,
  },
  bigtext: {
    fontFamily: fontFamily.bold,
    color: colors.white,
    fontSize: fontSize.semiLarge,
    marginTop: responsiveHeight(5),
    alignSelf: 'center',
  },
  desc: {
    fontSize: fontSize.addIc,
    color: '#FFFFFF50',
    width: responsiveWidth(80),
    fontFamily: fontFamily.regular,
  },
  textinput: {
    marginTop: spaceVertical.normal,
    width: responsiveWidth(80),
    fontSize: fontSize.small,
    fontFamily: fontFamily.bold,
    backgroundColor: colors.nocolor,
  },
  top: {
    marginTop: spaceVertical.semiSmall,
  },
  bigtextinput: {
    marginTop: spaceVertical.normal,
    width: responsiveWidth(80),
    fontSize: fontSize.small,
    fontFamily: fontFamily.bold,
    backgroundColor: colors.nocolor,
    height: responsiveHeight(25),
  },
  zipinput: {
    textAlign: 'center',
    width: responsiveWidth(30),
    fontSize: fontSize.small,
    fontFamily: fontFamily.bold,
    backgroundColor: colors.nocolor,
    bottom: 5,
  },
  doctext: {
    color: colors.white,
    fontFamily: fontFamily.bold,
    fontSize: fontSize.tileHeader,
    width: responsiveWidth(50),
  },
  docview: {
    height: responsiveHeight(8),
    backgroundColor: colors.bacgray,
    marginTop: spaceVertical.semiSmall,
    borderRadius: borderRadius.large,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  btn: {
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.projectgreen,
    height: responsiveHeight(7),
    width: responsiveWidth(60),
    borderRadius: borderRadius.semiLarge,
    marginTop: spaceVertical.small,
  },
  chfile: {
    alignSelf: 'center',
    fontFamily: fontFamily.bold,
    color: colors.white,
    fontSize: fontSize.medium,
  },
  fileContainer: {
    borderStyle: 'dashed',
    height: responsiveHeight(40),
    width: responsiveWidth(80),
    borderColor: colors.white,
    borderWidth: 1,
    borderRadius: 4,
    marginTop: spaceVertical.semiSmall,
  },
  selectLogo: {
    height: responsiveHeight(12),
    width: responsiveWidth(24),
    alignSelf: 'center',
    marginTop: spaceVertical.small,
    tintColor: colors.white,
    opacity: 0.8,
  },
  uploadText: {
    color: colors.white,
    alignSelf: 'center',
    fontFamily: fontFamily.medium,
  },
});

export {styles};
